# Generated by Django 5.0.6 on 2024-06-05 17:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Usuario',
            new_name='User',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='author',
        ),
        migrations.AddField(
            model_name='loan',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='biblioteca.user'),
            preserve_default=False,
        ),
    ]
