# Generated by Django 5.0.6 on 2024-06-05 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0002_rename_usuario_user_remove_loan_author_loan_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='date_publication',
            new_name='date_publishing',
        ),
    ]
